### ISSUE TITLE
Fail to run the command "azd provision" in windows

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/langfuse-on-azure#1]
**Describe the issue:**
Run command `azd provision` according to [Readme](https://github.com/Azure-Samples/langfuse-on-azure?tab=readme-ov-file#deploying-to-azure), deployment in windows is not supported.
![image](https://github.com/Azure-Samples/langfuse-on-azure/assets/138087452/212222e5-9a25-404e-89eb-0dbddd41dbdb)

**Repro Steps:**

1. Run `azd init -t langfuse-on-azure`.
2. Run `azd auth login`.
3. Run `pip install -r requirements.txt`.
4. Run `azd env new`.
5. Run `azd provision`.

**Environments:**
- azd version: daily
- os: windows

**Suggestion:**
Add hooks to support windows env.

**Expected behavior:**
Run the command `azd provision` successfully.

@pamelafox and @hemarina for notification

**Comment by pamelafox** [comment]
Can you try it now?

**Comment by v-xuto** [comment]
We have tried it and this issue has been fixed.
