### ISSUE TITLE
ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'authclientsecret' are invalid: value or keyVaultUrl and identity should be provided.

### ISSUE THREAD

**Issue by TerryCM** [Azure-Samples/langfuse-on-azure#12]
Getting this error despite following all the instructions on the read me, I tested locally and via Github codespaces:

ERROR: deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'container' is not valid according to the validation procedure. The tracking id is '34707f96-61d9-475b-b762-07dc06ffaddc'. See inner errors for details.
ValidationForResourceFailed: Validation failed for a resource. Check 'Error.Details[0]' for more information.
ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'authclientsecret' are invalid: value or keyVaultUrl and identity should be provided.

TraceID: 7d3eb78f588f88bfb4ed8c6815c25125
![image](https://github.com/Azure-Samples/langfuse-on-azure/assets/33166112/635d39c4-17b3-412a-b448-cf54a9353b08)

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by stphnthiel** [comment]
Any idea for a fix? It looks like there is a config issue when not using Entra auth.

**Comment by pamelafox** [comment]
Taking a look now!

**Comment by pamelafox** [comment]
Fixed, just change this line:
https://github.com/Azure-Samples/langfuse-on-azure/pull/13/files#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R168
Thanks for filing!
